name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        run: |
          echo "Deploying to server..."
          # TODO: coloque aqui seus comandos de deploy, por exemplo:
          # scp -r . user@servidor:/caminho/do/projeto
          # ssh user@servidor 'cd /caminho/do/projeto && ./deploy.sh'
