name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Sistema operacional onde o workflow rodará

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Baixa o código do repositório

      - name: Set up Python
        uses: actions/setup-python@v2  # Instala o Python
        with:
          python-version: '3.8'  # Versão do Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala as dependências do projeto

      - name: Run tests
        run: |
          pytest  # Executa os testes com pytest
